import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "@/components/ThemeProvider"
import { ReactNode } from "react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { cn } from "@/lib/utils"
import { defaultFontMapper } from "@/styles/fonts"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: { children: ReactNode }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={cn(...Object.values(defaultFontMapper))}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="container ">
              {children}
            </main>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
